### PR TITLE
Lute/theory parser literals

### PR DESCRIPTION
**Pull request by lute47lillo**
I've merged the latest changes you have made as jorge/deathcode. I've seen you have deleted the formatting for running the tests. Is that something we want to keep? Or the new view you think is better for later checks?

### CODE REVIEW

**Comment by lute47lillo** [comment]
I open a similar thread on the issue #16. The problem I have encountered is that if we use the function theory_term_to_literal, there are a theory terms that are ASTType.TheoryAtomElement, but the function does not check for those.

Therefore raising an error: no Attribute location because the Literal hasn't been created.

I think that theory_term_to_literal on ast.py from clingox library has to be updated, or there will still be failures due to that.

**Comment by jorgefandinno** [comment]
> I've seen you have deleted the formatting for running the tests. Is that something we want to keep? Or the new view you think is better for later checks?

What do you mean by "the formatting for running the tests"?

**Comment by jorgefandinno** [comment]
> I open a similar thread on the issue #16. The problem I have encountered is that if we use the function theory_term_to_literal, there are a theory terms that are ASTType.TheoryAtomElement, but the function does not check for those.
> 
> Therefore raising an error: no Attribute location because the Literal hasn't been created.
> 
> I think that theory_term_to_literal on ast.py from clingox library has to be updated, or there will still be failures due to that.

You are right. I added an adapter function.

Functionality tests are passing, but coverage is now failing.
Please clean up if necessary and check for death code generated after this patch.

Thanks

**Comment by lute47lillo** [comment]
> > I open a similar thread on the issue #16. The problem I have encountered is that if we use the function theory_term_to_literal, there are a theory terms that are ASTType.TheoryAtomElement, but the function does not check for those.
> > Therefore raising an error: no Attribute location because the Literal hasn't been created.
> > I think that theory_term_to_literal on ast.py from clingox library has to be updated, or there will still be failures due to that.
> 
> You are right. I added an adapter function.
> 
> Functionality tests are passing, but coverage is now failing. Please clean up if necessary and check for death code generated after this patch.
> 
> Thanks

I have removed the file theory_parser_literals.py since now is using the clingox counterpart.

I have added coverage for all tests. I'll made this PR ready for review so you can check the changes. I think all is in order now.

**Review by jorgefandinno — APPROVED** [review]

**Pull request merged**
