### PR TITLE
Lute/only reification

### PR DESCRIPTION
**Pull request by lute47lillo**
Updating all tests and removing non-reification functionality as per issue #52.

### CODE REVIEW

**Comment by lute47lillo** [comment]
@jorgefandinno I have pushed the latest changes regarding what we discussed today. All tests pass. There is just one exception: 
For the yale tests in both test_app.py and test_eclingo_examples.py and for tests yale 5, 7 and 8 it takes an extremely long time to compute. Even not finishing. 

Maybe an error in the new code that drops performance? Would you mind taking a look to see if there is not something obvious that might be causing that?

**Review by jorgefandinno — APPROVED** [review]

**Comment by jorgefandinno** [comment]
> @jorgefandinno I have pushed the latest changes regarding what we discussed today. All tests pass. There is just one exception: For the yale tests in both test_app.py and test_eclingo_examples.py and for tests yale 5, 7 and 8 it takes an extremely long time to compute. Even not finishing.
> 
> Maybe an error in the new code that drops performance? Would you mind taking a look to see if there is not something obvious that might be causing that?

In this branch? I just run them and they finish all in around 15s

```
fandinno@IST-jfandinno:~/student-research/eclingo (lute/only_reification)
$python -m unittest tests/test_eclingo_examples.py 
.<string>:1:13-14: info: atom does not occur in any rule head:
  u(b)

.The show statement rule:  show_statement(occurs(X0,X1)) :- u(occurs(X0,X1)).
The show statement rule:  show_statement(occurs(X0,X1)) :- u(occurs(X0,X1)).
The show statement rule:  show_statement(occurs(X0,X1)) :- u(occurs(X0,X1)).
The show statement rule:  show_statement(occurs(X0,X1)) :- u(occurs(X0,X1)).
.
----------------------------------------------------------------------
Ran 3 tests in 15.735s

OK
```

I also run the following command  which produces an empty world view
```
$eclingo 0 yale-parameter.lp input/yale05.lp -c length=5
The show statement rule:  show_statement(occurs(X0,X1)) :- u(occurs(X0,X1)).
Solving...
World view: 1

SATISFIABLE
```
while the expected answer is the following
```
$cat output/sol_yale05.txt 
[
[&k{occurs(aim,0)}, &k{occurs(aim,3)}, &k{occurs(load,2)}, &k{occurs(pull_trigger,1)}, &k{occurs(pull_trigger,4)}]
]
```

Is this what you get?

**Comment by lute47lillo** [comment]
> > @jorgefandinno I have pushed the latest changes regarding what we discussed today. All tests pass. There is just one exception: For the yale tests in both test_app.py and test_eclingo_examples.py and for tests yale 5, 7 and 8 it takes an extremely long time to compute. Even not finishing.
> > Maybe an error in the new code that drops performance? Would you mind taking a look to see if there is not something obvious that might be causing that?
> 
> In this branch? I just run them and they finish all in around 15s
> 
> ```
> fandinno@IST-jfandinno:~/student-research/eclingo (lute/only_reification)
> $python -m unittest tests/test_eclingo_examples.py 
> .<string>:1:13-14: info: atom does not occur in any rule head:
>   u(b)
> 
> .The show statement rule:  show_statement(occurs(X0,X1)) :- u(occurs(X0,X1)).
> The show statement rule:  show_statement(occurs(X0,X1)) :- u(occurs(X0,X1)).
> The show statement rule:  show_statement(occurs(X0,X1)) :- u(occurs(X0,X1)).
> The show statement rule:  show_statement(occurs(X0,X1)) :- u(occurs(X0,X1)).
> .
> ----------------------------------------------------------------------
> Ran 3 tests in 15.735s
> 
> OK
> ```
> 
> I also run the following command which produces an empty world view
> 
> ```
> $eclingo 0 yale-parameter.lp input/yale05.lp -c length=5
> The show statement rule:  show_statement(occurs(X0,X1)) :- u(occurs(X0,X1)).
> Solving...
> World view: 1
> 
> SATISFIABLE
> ```
> 
> while the expected answer is the following
> 
> ```
> $cat output/sol_yale05.txt 
> [
> [&k{occurs(aim,0)}, &k{occurs(aim,3)}, &k{occurs(load,2)}, &k{occurs(pull_trigger,1)}, &k{occurs(pull_trigger,4)}]
> ]
> ```
> 
> Is this what you get?

It is because there is a missing input file. The full command should be:

**eclingo tests/yale/yale.lp tests/yale/input/yale05.lp tests/yale/yale-parameter.lp -c length=5 0**

the yale.lp file was missing. 

Regarding the tests, I have commented out 5, 7 and 8 on test_eclingo_examples and 7 and 8 on test_app for the github push. That's why they all pass. If you run them independently they keep running forever. Could it be due to the last call to grounding in the WView in order to get the show?

**Comment by jorgefandinno** [comment]
Ok, I will look at this.

It seems that several test in tests.test_show fail and this is not part of the nox file.

Can you look into this?

**Comment by lute47lillo** [comment]
> Ok, I will look at this.
> 
> It seems that several test in tests.test_show fail and this is not part of the nox file.
> 
> Can you look into this?
> 
> Yes! That's because is using the Helper to create World Views. Old version. I'll push a fix later today.

Btw, in the case of a program such as: `"a :- &k{b}. b."`
If we do `#show b/0.` It obviously prints `&k{b}`, but if we do `#show a/0.` We will be giving a show_statement that is not possible. Meaning that there is no World View that contains `&k{a}`. In that case, should it print empty? Or should it print the only and true World View `&k{b} `even though we have not "asked for it".

**Comment by jorgefandinno** [comment]
> > Ok, I will look at this.
> > It seems that several test in tests.test_show fail and this is not part of the nox file.
> > Can you look into this?
> > Yes! That's because is using the Helper to create World Views. Old version. I'll push a fix later today.
> 
> Btw, in the case of a program such as: `"a :- &k{b}. b."` If we do `#show b/0.` It obviously prints `&k{b}`, but if we do `#show a/0.` We will be giving a show_statement that is not possible. Meaning that there is no World View that contains `&k{a}`. In that case, should it print empty? Or should it print the only and true World View `&k{b} `even though we have not "asked for it".

In the only world view of that program &k{a} is true, so that is what it should print. If you consider program  
```
a :- not &k{b}. 
b.
#show a/0.
``` 
were &k{a} is not ture, the answer should be empty.

**Comment by lute47lillo** [comment]
> > > Ok, I will look at this.
> > > It seems that several test in tests.test_show fail and this is not part of the nox file.
> > > Can you look into this?
> > > Yes! That's because is using the Helper to create World Views. Old version. I'll push a fix later today.
> > 
> > 
> > Btw, in the case of a program such as: `"a :- &k{b}. b."` If we do `#show b/0.` It obviously prints `&k{b}`, but if we do `#show a/0.` We will be giving a show_statement that is not possible. Meaning that there is no World View that contains `&k{a}`. In that case, should it print empty? Or should it print the only and true World View `&k{b} `even though we have not "asked for it".
> 
> In the only world view of that program
> 
> ```
> a :- &k{b}. 
> b.
> #show b/0.
> ```
> 
> &k{a} is true, so that is what it should print. If you consider program
> 
> ```
> a :- not &k{b}. 
> b.
> #show b/0.
> ```
> 
> were &k{a} is not ture, the answer should be empty.

```
a :- &k{b}. 
b.
#show b/0.
```
Is not &k{b} rather than &k{a}?

**Comment by jorgefandinno** [comment]
> > > > Ok, I will look at this.
> 
> > > > It seems that several test in tests.test_show fail and this is not part of the nox file.
> 
> > > > Can you look into this?
> 
> > > > Yes! That's because is using the Helper to create World Views. Old version. I'll push a fix later today.
> 
> > > 
> 
> > > 
> 
> > > Btw, in the case of a program such as: `"a :- &k{b}. b."` If we do `#show b/0.` It obviously prints `&k{b}`, but if we do `#show a/0.` We will be giving a show_statement that is not possible. Meaning that there is no World View that contains `&k{a}`. In that case, should it print empty? Or should it print the only and true World View `&k{b} `even though we have not "asked for it".
> 
> > 
> 
> > In the only world view of that program
> 
> > 
> 
> > ```
> 
> > a :- &k{b}. 
> 
> > b.
> 
> > #show b/0.
> 
> > ```
> 
> > 
> 
> > &k{a} is true, so that is what it should print. If you consider program
> 
> > 
> 
> > ```
> 
> > a :- not &k{b}. 
> 
> > b.
> 
> > #show b/0.
> 
> > ```
> 
> > 
> 
> > were &k{a} is not ture, the answer should be empty.
> 
> 
> 
> ```
> 
> a :- &k{b}. 
> 
> b.
> 
> #show b/0.
> 
> ```
> 
> Shouldn't it be &k{b} rather than &k{a}?

Right.

In the only world view of that program
```
a :- &k{b}. 
b.
#show a/0.
``` 
&k{a} is true, so that is what it should print. If you consider program  
```
a :- not &k{b}. 
b.
#show a/0.
``` 
were &k{a} is not ture, the answer should be empty.

**Comment by lute47lillo** [comment]
@jorgefandinno I'm going to go ahead and merge it into reification. After cleaning up tests and adding the optimization it all looks good.

I'll start working on the benchmarks shortly.

**Pull request merged**
